from pathlib import Path
ARCHIVO_INTEGRADOR = Path(__file__).parent.parent.parent # EN ESTA VARIABLE TENGO TODA LA INFO DE LA CARPETA INTEGRADOR
ARCHIVO_EPH = ARCHIVO_INTEGRADOR / "archivos" # EN ESTA VARIABLE ESTOY PARADO EN LA RUTA DE TODOS LOS DOCUMENTOS DESCARGADOS 
print(ARCHIVO_INTEGRADOR)
MAESTRO_HOGARES = ARCHIVO_EPH / "archivo_hogares.txt"
MAESTRO_INDIVIDUO = ARCHIVO_EPH / "archivo_individuos.txt"